# Generated by Django 3.1.3 on 2020-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintTitle', models.CharField(max_length=32)),
                ('complaintDesc', models.CharField(max_length=255)),
                ('complaintImg', models.CharField(max_length=255)),
            ],
        ),
    ]
